//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPAddin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\_School\\\\BP\\\\funkcny_prototyp\\\\BP_ADDIN\\\\class_generation_output")]
        public string GeneratedDir {
            get {
                return ((string)(this["GeneratedDir"]));
            }
            set {
                this["GeneratedDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\_School\\\\BP\\\\funkcny_prototyp\\\\project")]
        public string ProjectDir {
            get {
                return ((string)(this["ProjectDir"]));
            }
            set {
                this["ProjectDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\_School\\\\BP\\\\funkcny_prototyp\\\\BP_ADDIN\\\\BPAddin\\\\BPAddin\\\\UI_Library")]
        public string UILibraryDir {
            get {
                return ((string)(this["UILibraryDir"]));
            }
            set {
                this["UILibraryDir"] = value;
            }
        }
    }
}
