///////////////////////////////////////////////////////////
//  scrMain.cs
//  Implementation of the Class scrMain
//  Generated by Enterprise Architect
//  Created on:      12-mar-2026 12:16:57
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class scrMain {

	public scrMain(){

	}

	~scrMain(){

	}

}//end scrMain