///////////////////////////////////////////////////////////
//  testClass.cs
//  Implementation of the Class testClass
//  Generated by Enterprise Architect
//  Created on:      12-mar-2026 12:16:57
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class testClass {

	public testClass(){

	}

	~testClass(){

	}

}//end testClass