///////////////////////////////////////////////////////////
//  airport.cs
//  Implementation of the Class airport
//  Generated by Enterprise Architect
//  Created on:      05-mar-2026 14:07:37
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class airport {

	public runway m_runway;
	public route m_route;
	public hangar m_hangar;

	public airport(){

	}

	~airport(){

	}

}//end airport