///////////////////////////////////////////////////////////
//  airplane.cs
//  Implementation of the Class airplane
//  Generated by Enterprise Architect
//  Created on:      05-mar-2026 14:07:36
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class airplane {

	public passenger m_passenger;

	public airplane(){

	}

	~airplane(){

	}

	/* Begin - EA generated code for  Activities and Interactions */

	public void init()
	{
		// behavior is a Activity
		public string model = "Boeing";
		public string airline = "Ryanair";
	}


	/* End - EA generated code for  Activities and Interactions */

}//end airplane