///////////////////////////////////////////////////////////
//  flight.cs
//  Implementation of the Class flight
//  Generated by Enterprise Architect
//  Created on:      05-mar-2026 14:07:37
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class flight {

	public ticket m_ticket;
	public airplane m_airplane;

	public flight(){

	}

	~flight(){

	}

}//end flight