///////////////////////////////////////////////////////////
//  ticket.cs
//  Implementation of the Class ticket
//  Generated by Enterprise Architect
//  Created on:      05-mar-2026 14:07:37
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ticket {

	public passenger m_passenger;

	public ticket(){

	}

	~ticket(){

	}

}//end ticket