///////////////////////////////////////////////////////////
//  buttonOK.cs
//  Implementation of the Class buttonOK
//  Generated by Enterprise Architect
//  Created on:      16-apr-2026 13:40:06
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
public class buttonOK : UIButton {

	public buttonOK(){

	}

	~buttonOK(){

	}

}//end buttonOK