///////////////////////////////////////////////////////////
//  buttonHelp.cs
//  Implementation of the Class buttonHelp
//  Generated by Enterprise Architect
//  Created on:      19-mar-2026 14:54:58
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
public class buttonHelp : UIButton {

	public screenScreenA m_screenScreenA;

	public buttonHelp(){

	}

	~buttonHelp(){

	}

}//end buttonHelp