///////////////////////////////////////////////////////////
//  buttonAddTask.cs
//  Implementation of the Class buttonAddTask
//  Generated by Enterprise Architect
//  Created on:      29-apr-2026 21:56:44
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
namespace ApplicationModel {
	public class buttonAddTask : UIButton {

		public buttonAddTask(){

		}

		~buttonAddTask(){

		}

	}//end buttonAddTask

}//end namespace ApplicationModel