///////////////////////////////////////////////////////////
//  buttonSave.cs
//  Implementation of the Class buttonSave
//  Generated by Enterprise Architect
//  Created on:      28-apr-2026 18:24:21
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
namespace ApplicationModel {
	public class buttonSave : UIButton {

		public buttonSave(){

		}

		~buttonSave(){

		}

	}//end buttonSave

}//end namespace ApplicationModel