///////////////////////////////////////////////////////////
//  buttonCancel.cs
//  Implementation of the Class buttonCancel
//  Generated by Enterprise Architect
//  Created on:      19-mar-2026 17:38:38
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
public class buttonCancel : UIButton {

	public screenScreenA m_screenScreenA;

	public buttonCancel(){

	}

	~buttonCancel(){

	}

	public override void onClick(){

	}

}//end buttonCancel