///////////////////////////////////////////////////////////
//  buttonOK.cs
//  Implementation of the Class buttonOK
//  Generated by Enterprise Architect
//  Created on:      19-mar-2026 14:54:58
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
public class buttonOK : UIButton {

	public screenScreenA m_screenScreenA;

	public buttonOK(){

	}

	~buttonOK(){

	}

}//end buttonOK