///////////////////////////////////////////////////////////
//  buttonClose.cs
//  Implementation of the Class buttonClose
//  Generated by Enterprise Architect
//  Created on:      28-apr-2026 18:24:21
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
namespace ApplicationModel {
	public class buttonClose : UIButton {

		public buttonClose(){

		}

		~buttonClose(){

		}

	}//end buttonClose

}//end namespace ApplicationModel