///////////////////////////////////////////////////////////
//  labelDescription.cs
//  Implementation of the Class labelDescription
//  Generated by Enterprise Architect
//  Created on:      29-apr-2026 21:56:44
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
namespace ApplicationModel {
	public class labelDescription : UILabel {

		public labelDescription(){

		}

		~labelDescription(){

		}

	}//end labelDescription

}//end namespace ApplicationModel