///////////////////////////////////////////////////////////
//  labelLabelA.cs
//  Implementation of the Class labelLabelA
//  Generated by Enterprise Architect
//  Created on:      16-apr-2026 13:40:06
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
public class labelLabelA : UILabel {

	public labelLabelA(){

	}

	~labelLabelA(){

	}

}//end labelLabelA