///////////////////////////////////////////////////////////
//  listBoxListBox.cs
//  Implementation of the Class listBoxListBox
//  Generated by Enterprise Architect
//  Created on:      28-apr-2026 18:24:21
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
namespace ApplicationModel {
	public class listBoxListBox : UIListBox {

		public listBoxListBox(){

		}

		~listBoxListBox(){

		}

	}//end listBoxListBox

}//end namespace ApplicationModel