///////////////////////////////////////////////////////////
//  screenScreenA.cs
//  Implementation of the Class screenScreenA
//  Generated by Enterprise Architect
//  Created on:      18-mar-2026 22:21:46
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
public partial class screenScreenA : UIScreen {



	~screenScreenA(){

	}

	public screenScreenA(){

		InitializeComponent();
	}

}//end screenScreenA