///////////////////////////////////////////////////////////
//  screenScreenA.cs
//  Implementation of the Class screenScreenA
//  Generated by Enterprise Architect
//  Created on:      19-mar-2026 17:38:38
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
public partial class screenScreenA : UIScreen {



	~screenScreenA(){

	}

	public screenScreenA(){

		InitializeComponent();
	}

}//end screenScreenA