///////////////////////////////////////////////////////////
//  screenAddTask.cs
//  Implementation of the Class screenAddTask
//  Generated by Enterprise Architect
//  Created on:      29-apr-2026 21:56:44
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
using ApplicationModel;
namespace ApplicationModel {
	public partial class screenAddTask : UIScreen {

		public ApplicationModel.labelAddTaskDescription m_labelAddTaskDescription;
		public ApplicationModel.buttonCancel m_buttonCancel;
		public ApplicationModel.buttonSave m_buttonSave;
		public ApplicationModel.labelTaskDescription m_labelTaskDescription;
		public ApplicationModel.textBoxTaskName m_textBoxTaskName;



		~screenAddTask(){

		}

		public screenAddTask(){

			InitializeComponent();
		}

		/* Begin - EA generated code for  Activities and Interactions */

		public void onbuttonSaveClick()
		{
			// behavior is a Activity
			screenMain.Instance.addTask(textBoxTaskName.Text)

			;
			MessageBox.Show("Text Spravy");
			screenMain.Instance.Show();
			this.Close();
		}


		/* End - EA generated code for  Activities and Interactions */

	}//end screenAddTask

}//end namespace ApplicationModel