///////////////////////////////////////////////////////////
//  screenAddTaskScreen.cs
//  Implementation of the Class screenAddTaskScreen
//  Generated by Enterprise Architect
//  Created on:      28-apr-2026 18:24:22
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
using ApplicationModel;
namespace ApplicationModel {
	public partial class screenAddTaskScreen : UIScreen {

		public ApplicationModel.buttonSave m_buttonSave;
		public ApplicationModel.labelTaskDescription m_labelTaskDescription;
		public ApplicationModel.textBoxTaskName m_textBoxTaskName;
		public ApplicationModel.buttonCancel m_buttonCancel;



		~screenAddTaskScreen(){

		}

		public screenAddTaskScreen(){

			InitializeComponent();
		}

		/* Begin - EA generated code for  Activities and Interactions */

		public void onbuttonSaveClick()
		{
			// behavior is a Activity
			screenScreenMain.Instance.addTask(textBoxTaskName.Text);
			MessageBox.Show("Uložená");
			screenScreenMain.Instance.Show();
			this.Close();
		}

		public void onbuttonCancelClick()
		{
			// behavior is a Activity
			this.Close();
			screenScreenMain.Instance.Show();
		}


		/* End - EA generated code for  Activities and Interactions */

	}//end screenAddTaskScreen

}//end namespace ApplicationModel