///////////////////////////////////////////////////////////
//  screenScreenA.cs
//  Implementation of the Class screenScreenA
//  Generated by Enterprise Architect
//  Created on:      16-apr-2026 13:40:06
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
public partial class screenScreenA : UIScreen {

	public buttonCancel m_buttonCancel;
	public textBoxEditControlA m_textBoxEditControlA;
	public labelLabelA m_labelLabelA;
	public buttonOK m_buttonOK;



	~screenScreenA(){

	}

	public screenScreenA(){

		InitializeComponent();
	}

}//end screenScreenA