///////////////////////////////////////////////////////////
//  screenScreenMain.cs
//  Implementation of the Class screenScreenMain
//  Generated by Enterprise Architect
//  Created on:      28-apr-2026 18:24:23
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
using ApplicationModel;
namespace ApplicationModel {
	public partial class screenScreenMain : UIScreen {

		public ApplicationModel.buttonAddTask m_buttonAddTask;
		public ApplicationModel.buttonClose m_buttonClose;
		public ApplicationModel.labelDescription m_labelDescription;
		public ApplicationModel.listBoxListBox m_listBoxListBox;



		~screenScreenMain(){

		}

		public screenScreenMain(){

			InitializeComponent();
		}

		/// 
		/// <param name="name"></param>
		public void addTask(string name){

			listBoxListBox.Items.Add(name);
		}

		/* Begin - EA generated code for  Activities and Interactions */

		public void onbuttonAddTaskClick()
		{
			// behavior is a Activity
			new screenAddTaskScreen().Show(); this.Hide();
		}

		public void onbuttonCloseClick()
		{
			// behavior is a Activity
			this.Close();
		}


		/* End - EA generated code for  Activities and Interactions */

	}//end screenScreenMain

}//end namespace ApplicationModel