///////////////////////////////////////////////////////////
//  screenMain.cs
//  Implementation of the Class screenMain
//  Generated by Enterprise Architect
//  Created on:      29-apr-2026 21:56:45
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
using ApplicationModel;
namespace ApplicationModel {
	public partial class screenMain : UIScreen {

		public ApplicationModel.buttonAddTask m_buttonAddTask;
		public ApplicationModel.buttonClose m_buttonClose;
		public ApplicationModel.labelDescription m_labelDescription;
		public ApplicationModel.listBoxTasks m_listBoxTasks;



		~screenMain(){

		}

		public screenMain(){

			InitializeComponent();
		}

		/// 
		/// <param name="name"></param>
		public void addTask(string name){

			listBoxTasks.Items.Add(name);
		}

	}//end screenMain

}//end namespace ApplicationModel