///////////////////////////////////////////////////////////
//  textBoxTaskName.cs
//  Implementation of the Class textBoxTaskName
//  Generated by Enterprise Architect
//  Created on:      29-apr-2026 21:56:46
//  Original author: danir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BPAddin;
namespace ApplicationModel {
	public class textBoxTaskName : UITextBox {

		public textBoxTaskName(){

		}

		~textBoxTaskName(){

		}

	}//end textBoxTaskName

}//end namespace ApplicationModel